apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: database-pod
  name: database-deployment
spec:
  selector:
    matchLabels:
      app: database-pod
  replicas: 1
  template:
    metadata:
      labels:
        app: database-pod
    spec:
      containers:
        - name: database
          volumeMounts:
            - mountPath: /data/db
              name: database-data
          image: docker.io/mongo:4.4.4
          ports:
            - containerPort: 27017
              hostPort: 27017
          resources: {}
      volumes:
        - name: database-data
          hostPath:
            path: /home/applegamer22/Documents/scr-web/database
      restartPolicy: OnFailure