name: Publish Image
on:
  release:
    types: [published]
jobs:
  publish-image-docker:
    runs-on: ubuntu-latest
    steps:
      - name: Pull Source Code
        uses: actions/checkout@v2.3.4
      - name: Set-up QEMU
        uses: docker/setup-qemu-action@v1.2.0
      - name: Set-up Docker BuildX
        uses: docker/setup-buildx-action@v1.4.1
      - name: Login to Docker Hub
        uses: docker/login-action@v1.10.0
        with:
          username: ${{secrets.DOCKERHUB_USERNAME}}
          password: ${{secrets.DOCKERHUB_TOKEN}}
      - name: Get Release Version
        id: get_version
        run: echo ::set-output name=VERSION::${GITHUB_REF##*/}
      - name: Extract Metadata for Docker
        id: meta
        uses: docker/metadata-action@v3.3.0
        with:
          images: ${{secrets.DOCKERHUB_USERNAME}}/scr-web
          tags: |
            type=raw,value=${{steps.get_version.outputs.VERSION}}
            latest
      - name: Build & Push to Docker Hub
        uses: docker/build-push-action@v2.5.0
        with:
          push: true
          tags: ${{steps.meta.outputs.tags}}
          labels: ${{steps.meta.outputs.labels}}
          platforms: linux/amd64,linux/arm64,linux/arm/v6,linux/arm/v7,linux/s390x,linux/ppc64le
  publish-image-github:
    runs-on: ubuntu-latest
    permissions:
      packages: write
      contents: read
    steps:
      - name: Pull Source Code
        uses: actions/checkout@v2.3.4
      - name: Set-up QEMU
        uses: docker/setup-qemu-action@v1.2.0
      - name: Set-up Docker BuildX
        uses: docker/setup-buildx-action@v1.4.1
      - name: Log in to GitHub Container Registry
        uses: docker/login-action@v1.10.0
        with:
          registry: ghcr.io
          username: ${{github.repository_owner}}
          password: ${{secrets.GITHUB_TOKEN}}
      - name: Get Release Version
        id: get_version
        run: echo ::set-output name=VERSION::${GITHUB_REF##*/}
      - name: Extract Metadata for Docker
        id: meta
        uses: docker/metadata-action@v3.3.0
        with:
          images: ghcr.io/${{github.repository}}
          tags: |
            type=raw,value=${{steps.get_version.outputs.VERSION}}
            latest
      - name: Build & Push to GitHub Container Registry
        uses: docker/build-push-action@v2.5.0
        with:
          push: true
          tags: ${{steps.meta.outputs.tags}}
          labels: ${{steps.meta.outputs.labels}}
          platforms: linux/amd64,linux/arm64,linux/arm/v6,linux/arm/v7,linux/s390x,linux/ppc64le
